/** @type {import('tailwindcss').Config} */
export default {
    content: ['./src/**/*.{html,jsx,js}'],
    theme: {
      extend: {
        fontFamily: {
          sans: ['DM Sans', 'sans-serif'],
        },
        colors: {
          light: {
            primary: '#205781',
            surfaceTint: '#205781',
            onPrimary: '#FFFFFF',
            primaryContainer: '#98D2C0',
            onPrimaryContainer: '#0A1E2B',
            secondary: '#4F959D',
            onSecondary: '#FFFFFF',
            secondaryContainer: '#F6F8D5',
            onSecondaryContainer: '#1A3235',
            tertiary: '#4F959D',
            onTertiary: '#FFFFFF',
            tertiaryContainer: '#F6F8D5',
            onTertiaryContainer: '#1A3235',
            error: '#BA1A1A',
            onError: '#FFFFFF',
            errorContainer: '#FFDAD6',
            onErrorContainer: '#410002',
            background: '#F6F8D5',
            onBackground: '#121212',
            surface: '#F6F8D5',
            onSurface: '#121212',
            surfaceVariant: '#DCE5E6',
            onSurfaceVariant: '#3F4A4B',
            outline: '#6F797A',
            outlineVariant: '#C1CBCC',
            shadow: '#000000',
            scrim: '#000000',
            inverseSurface: '#2B3233',
            inverseOnSurface: '#ECF1F2',
            inversePrimary: '#98D2C0',
            primaryFixed: '#98D2C0',
            onPrimaryFixed: '#0A1E2B',
            primaryFixedDim: '#7BBCAA',
            onPrimaryFixedVariant: '#174560',
            secondaryFixed: '#F6F8D5',
            onSecondaryFixed: '#1A3235',
            secondaryFixedDim: '#D9DBBB',
            onSecondaryFixedVariant: '#3A7A80',
            tertiaryFixed: '#F6F8D5',
            onTertiaryFixed: '#1A3235',
            tertiaryFixedDim: '#D9DBBB',
            onTertiaryFixedVariant: '#3A7A80',
            surfaceDim: '#DADCBC',
            surfaceBright: '#F6F8D5',
            surfaceContainerLowest: '#FFFFFF',
            surfaceContainerLow: '#EFF1D0',
            surfaceContainer: '#E8EACB',
            surfaceContainerHigh: '#E2E4C6',
            surfaceContainerHighest: '#DCDEC1',
          },
          dark: {
            primary: '#98D2C0',
            surfaceTint: '#98D2C0',
            onPrimary: '#2C061F',
            primaryContainer: '#374045',
            onPrimaryContainer: '#B8F0DE',
            secondary: '#D89216',
            onSecondary: '#2C061F',
            secondaryContainer: '#374045',
            onSecondaryContainer: '#E1D89F',
            tertiary: '#D89216',
            onTertiary: '#2C061F',
            tertiaryContainer: '#374045',
            onTertiaryContainer: '#E1D89F',
            error: '#FFB4AB',
            onError: '#690005',
            errorContainer: '#93000A',
            onErrorContainer: '#FFDAD6',
            background: '#2C061F',
            onBackground: '#E1D89F',
            surface: '#2C061F',
            onSurface: '#E1D89F',
            surfaceVariant: '#374045',
            onSurfaceVariant: '#C1CBCC',
            outline: '#8A9597',
            outlineVariant: '#374045',
            shadow: '#000000',
            scrim: '#000000',
            inverseSurface: '#E1D89F',
            inverseOnSurface: '#2C061F',
            inversePrimary: '#205781',
            primaryFixed: '#98D2C0',
            onPrimaryFixed: '#0A1E2B',
            primaryFixedDim: '#7BBCAA',
            onPrimaryFixedVariant: '#174560',
            secondaryFixed: '#E1D89F',
            onSecondaryFixed: '#2C061F',
            secondaryFixedDim: '#C7C08C',
            onSecondaryFixedVariant: '#AA7412',
            tertiaryFixed: '#E1D89F',
            onTertiaryFixed: '#2C061F',
            tertiaryFixedDim: '#C7C08C',
            onTertiaryFixedVariant: '#AA7412',
            surfaceDim: '#2C061F',
            surfaceBright: '#432636',
            surfaceContainerLowest: '#25051A',
            surfaceContainerLow: '#2C061F',
            surfaceContainer: '#321B2A',
            surfaceContainerHigh: '#392631',
            surfaceContainerHighest: '#403039',
          },
        },
        space: {
          0: '0px',
          1: '4px',
          2: '8px',
          3: '12px',
          4: '16px',
          5: '20px',
          6: '24px',
          7: '28px',
          8: '32px',
          9: '36px',
          10: '40px',
          11: '44px',
          12: '48px',
          13: '52px',
          14: '56px',
          15: '60px',
          16: '64px',
          17: '68px',
          18: '72px',
          19: '76px',
          20: '80px',
          21: '84px',
          22: '88px',
          23: '92px',
          24: '96px',
          25: '100px',
          26: '104px',
          27: '108px',
          28: '112px',
          29: '116px',
          30: '120px',
        },
        boxShadow: {
          elevation1:
            '0px 1px 2px 0px rgba(0, 0, 0, 0.30), 0px 1px 3px 1px rgba(0, 0, 0, 0.15)',
          elevation2:
            '0px 1px 2px 0px rgba(0, 0, 0, 0.30), 0px 2px 6px 2px rgba(0, 0, 0, 0.15)',
          elevation3:
            '0px 4px 8px 3px rgba(0, 0, 0, 0.15), 0px 1px 3px 0px rgba(0, 0, 0, 0.30)',
          elevation4:
            '0px 6px 10px 4px rgba(0, 0, 0, 0.15), 0px 2px 3px 0px rgba(0, 0, 0, 0.30)',
          elevation5:
            '0px 8px 12px 6px rgba(0, 0, 0, 0.15), 0px 4px 4px 0px rgba(0, 0, 0, 0.30)',
        },
        borderRadius: {
          none: '0',
          extraSmall: '4px',
          small: '8px',
          medium: '12px',
          large: '16px',
          extraLarge: '28px',
          full: '1000px',
        },
        fontSize: {
          displayLarge: [
            '57px',
            {
              fontWeight: '400',
              lineHeight: '64px',
              letterSpacing: '-0.25px',
            },
          ],
          displayMedium: [
            '45px',
            {
              fontWeight: '400',
              lineHeight: '52px',
              letterSpacing: '0',
            },
          ],
          displaySmall: [
            '36px',
            {
              fontWeight: '400',
              lineHeight: '44px',
              letterSpacing: '0',
            },
          ],
          headlineLarge: [
            '32px',
            {
              fontWeight: '400',
              lineHeight: '40px',
              letterSpacing: '0',
            },
          ],
          headlineMedium: [
            '28px',
            {
              fontWeight: '400',
              lineHeight: '36px',
              letterSpacing: '0',
            },
          ],
          headlineSmall: [
            '24px',
            {
              fontWeight: '400',
              lineHeight: '32px',
              letterSpacing: '0',
            },
          ],
          titleLarge: [
            '22px',
            {
              fontWeight: '400',
              lineHeight: '28px',
              letterSpacing: '0',
            },
          ],
          titleMedium: [
            '16px',
            {
              fontWeight: '500',
              lineHeight: '24px',
              letterSpacing: '0.15px',
            },
          ],
          titleSmall: [
            '14px',
            {
              fontWeight: '500',
              lineHeight: '20px',
              letterSpacing: '0.1px',
            },
          ],
          bodyLarge: [
            '16px',
            {
              fontWeight: '400',
              lineHeight: '24px',
              letterSpacing: '0.5px',
            },
          ],
          bodyMedium: [
            '14px',
            {
              fontWeight: '400',
              lineHeight: '20px',
              letterSpacing: '0.25px',
            },
          ],
          bodySmall: [
            '12px',
            {
              fontWeight: '400',
              lineHeight: '16px',
              letterSpacing: '0.4px',
            },
          ],
          labelLarge: [
            '14px',
            {
              fontWeight: '500',
              lineHeight: '20px',
              letterSpacing: '0.1px',
            },
          ],
          labelMedium: [
            '12px',
            {
              fontWeight: '500',
              lineHeight: '16px',
              letterSpacing: '0.5px',
            },
          ],
          labelSmall: [
            '11px',
            {
              fontWeight: '500',
              lineHeight: '16px',
              letterSpacing: '0.5px',
            },
          ],
        },
        transitionDuration: {
          short1: '50ms',
          short2: '100ms',
          short3: '150ms',
          short4: '200ms',
          medium1: '250ms',
          medium2: '300ms',
          medium3: '350ms',
          medium4: '400ms',
          long1: '450ms',
          long2: '500ms',
          long3: '550ms',
          long4: '600ms',
          extraLong1: '700ms',
          extraLong2: '800ms',
          extraLong3: '900ms',
          extraLong4: '1000ms',
        },
        transitionDelay: {
          short1: '50ms',
          short2: '100ms',
          short3: '150ms',
          short4: '200ms',
          medium1: '250ms',
          medium2: '300ms',
          medium3: '350ms',
          medium4: '400ms',
          long1: '450ms',
          long2: '500ms',
          long3: '550ms',
          long4: '600ms',
          extraLong1: '700ms',
          extraLong2: '800ms',
          extraLong3: '900ms',
          extraLong4: '1000ms',
        },
        transitionTimingFunction: {
          standard: 'cubic-bezier(0.2, 0, 0, 1)',
          standardDecelerate: 'cubic-bezier(0, 0, 0, 1)',
          standardAccelerate: 'cubic-bezier(0.3, 0, 1, 1)',
          emphasized: 'cubic-bezier(0.2, 0, 0, 1.0)',
          emphasizedDecelerate: 'cubic-bezier(0.05, 0.7, 0.1, 1)',
          emphasizedAccelerate: 'cubic-bezier(0.3, 0, 0.8, 0.15)',
          legacy: 'cubic-bezier(0.4, 0, 0.2, 1.0)',
          legacyDecelerate: 'cubic-bezier(0, 0, 0.2, 1)',
          legacyAccelerate: 'cubic-bezier(0.4, 0, 1, 1)',
          linear: 'cubic-bezier(0, 0, 1, 1)',
        },
      },
    },
    plugins: [],
  };